---
- hosts: localhost
  name: Install & configure linux workstation
  remote_user: root
  roles:
    - packages
    - config
    - system

  vars_files:
    - vars/git.yml
    - vars/os.yml

# vim: set filetype=yaml.ansible
