---
- name: "Ensure packages are up-to-date"
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  tags: packages

- name: "Add Google gcloud (gcp) repository key"
  ansible.builtin.apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg" 
    state: present
  become: true

- name: "Add Google gcloud (gcp) repository"
  ansible.builtin.apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  become: true

- name: "Add Spotify repository key"
  ansible.builtin.apt_key:
    url: "https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg"
    state: present
  become: true

- name: "Add Spotify repository"
  ansible.builtin.apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: true

- name: "Add Hashicorp repository key"
  ansible.builtin.apt_key:
    url: "https://apt.releases.hashicorp.com/gpg" 
    state: present
  become: true

- name: "Add Hashicorp repository"
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ upstream_debian_codename }} main"
    state: present
  become: true

- name: "Install tools of the trade"
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    autoclean: true
    force: true
  tags: packages
