---
- name: Ensure packages are up-to-date
  become: true
  ansible.builtin.apt:
    name: "*"
    state: present
    update_cache: true
  tags: packages

- name: Add Google Cloud repository key
  ansible.builtin.apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present
  become: true

- name: Add Google Cloud repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  become: true

- name: Add Spotify repository key
  ansible.builtin.apt_key:
    url: "https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg"
    state: present
  become: true

- name: Add Spotify repository
  ansible.builtin.apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: true

- name: Add Hashicorp repository key
  ansible.builtin.apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present
  become: true

- name: Add Hashicorp repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ upstream_debian_codename }} main"
    state: present
  become: true

- name: Ensure apt Neovim is not installed
  become: true
  ansible.builtin.apt:
    name: neovim
    state: absent
  tags: packages

- name: Install Neovim latest stable release
  become: true
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    dest: /usr/local/bin/nvim
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  tags: packages

- name: "Create FiraCode font directory for {{ user }}"
  become: true
  ansible.builtin.file:
    path: "/home/{{ user }}/.fonts/FiraCode"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: packages

- name: Query Github API for the latest Nerd Fonts release
  ansible.builtin.uri:
    url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
    return_content: true
  register: nerdfonts_release
  tags: packages

- name: Install FiraCode latest release
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerdfonts_release.json.tag_name }}/FiraCode.tar.xz"
    remote_src: true
    dest: "/home/{{ user }}/.fonts/FiraCode/"
    mode: "0600"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: packages
- name: Query Github API for the latest Starship release
  ansible.builtin.uri:
    url: https://api.github.com/repos/starship/starship/releases/latest
    return_content: true
  register: starship_release
  tags: packages

- name: Install Starship latest release
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/starship/starship/releases/download/{{ starship_release.json.tag_name }}/starship-x86_64-unknown-linux-gnu.tar.gz"
    remote_src: true
    dest: /usr/local/bin/
    mode: "0755"
  tags: packages

- name: Query Github API for the latest Zellij release
  ansible.builtin.uri:
    url: https://api.github.com/repos/zellij-org/zellij/releases/latest
    return_content: true
  register: zellij_release
  tags: packages

- name: Install Zellij latest release
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/zellij-org/zellij/releases/download/{{ zellij_release.json.tag_name }}/zellij-x86_64-unknown-linux-musl.tar.gz"
    remote_src: true
    dest: /usr/local/bin/
    mode: "0755"
  tags: packages

- name: Check if Cargo is installed
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: which cargo
  failed_when: false
  register: cargo_installed
  changed_when: false
  tags: packages

- name: Download cargo Install script
  become: true
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  tags: packages
  when: cargo_installed.rc in [1]

- name: Install cargo
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: /tmp/sh.rustup.rs -y
  args:
    creates: "/home/{{ user }}/.cargo/bin/cargo"
  tags: packages
  when: cargo_installed.rc in [1]

- name: Install Alacritty & Zellij Runner
  become: true
  become_user: "{{ user }}"
  community.general.cargo:
    name: "{{ item }}"
    state: latest
  loop:
    - zellij-runner
    - alacritty
  tags: packages

- name: Add rust binaries to path
  ansible.builtin.file:
    src: "/home/{{ user }}/.cargo/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    state: link
  loop:
    - alacritty
    - cargo
    - cargo-clippy
    - cargo-fmt
    - cargo-miri
    - clippy-driver
    - rls
    - rust-analyzer
    - rustc
    - rustdoc
    - rustfmt
    - rust-gdb
    - rust-gdbgui
    - rust-lldb
    - rustup
    - zellij-runner
  tags: packages

- name: Install apt tools
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    autoclean: true
    force: true
  tags: packages

- name: Customize default screenkey display position
  become: true
  ansible.builtin.lineinfile:
    name: /usr/share/applications/screenkey.desktop
    state: present
    regexp: '^Exec'
    line: 'Exec=screenkey -p fixed --geometry 25%x10%+74%-50%'
  tags: packages
