---
- name: Ensure packages are up-to-date
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  tags: packages

- name: Add Google Cloud repository key
  ansible.builtin.apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg" 
    state: present
  become: true

- name: Add Google Cloud repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  become: true

- name: Add Spotify repository key
  ansible.builtin.apt_key:
    url: "https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg"
    state: present
  become: true

- name: Add Spotify repository
  ansible.builtin.apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: true

- name: Add Hashicorp repository key
  ansible.builtin.apt_key:
    url: "https://apt.releases.hashicorp.com/gpg" 
    state: present
  become: true

- name: Add Hashicorp repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ upstream_debian_codename }} main"
    state: present
  become: true

- name: Ensure apt Neovim is not installed
  become: true
  ansible.builtin.apt:
    name: neovim
    state: absent
  tags: packages

- name: Install Neovim latest stable release
  become: true
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    dest: /usr/local/bin/nvim
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: packages

- name: Query Github API for the latest Starship release
  run_once: true
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/starship/starship/releases/latest |
    jq -r ".tag_name"    
  register: starship_release
  changed_when: false
  tags: packages

- name: Install Starship latest release
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/starship/starship/releases/download/{{ starship_release.stdout }}/starship-x86_64-unknown-linux-gnu.tar.gz"
    remote_src: true
    dest: /usr/local/bin/
    mode: 0755
  tags: packages

- name: Install tools of the trade
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    autoclean: true
    force: true
  tags: packages
