---
- name: "Create user {{ user }}"
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    comment: "{{ user }}"
    groups: "{{ user }},cdrom,floppy,audio,dip,video,plugdev,users,netdev,bluetooth,lpadmin,scanner,sudo"
    shell: /bin/zsh
  tags: system
  when: ansible_facts['os_family'] == "Debian"

- name: "Create user {{ user }}"
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    comment: "{{ user }}"
    groups: "{{ user }},wheel"
    shell: /bin/zsh
  tags: system
  when: ansible_facts['os_family'] == "Archlinux"

- name: "Create sudo rules for user {{ user }}"
  become: true
  ansible.builtin.lineinfile:
    name: /etc/sudoers
    state: present
    regexp: '^{{ user }}'
    line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags: system

- name: "Create .ssh directory for {{ user }}"
  become: true
  ansible.builtin.file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: system

- name: Generate SSH key
  become: true
  community.crypto.openssh_keypair:
    path: "/home/{{ user }}/.ssh/id_ed25519"
    comment: "{{ user }}@{{ ansible_hostname }}"
    type: ed25519
    mode: "0400"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: system

- name: Change workstation hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ debian_host }}"
    use: debian
  tags: system
  when: ansible_facts['os_family'] == "Debian"

- name: Change workstation hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ arch_host }}"
    use: systemd
  tags: system
  when: ansible_facts['os_family'] == "Archlinux"
