---
- name: "Create user {{ user }}"
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    comment: "{{ user }}"
    groups: "{{ user }},cdrom,floppy,audio,dip,video,plugdev,users,netdev,docker,bluetooth,lpadmin,scanner,vboxusers,libvirt,gns3,sudo"
    shell: "/bin/zsh"

- name: "Create sudo rules for user {{ user }}"
  become: true
  ansible.builtin.lineinfile:
    name: /etc/sudoers
    state: present
    regexp: '^{{ user }}'
    line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: "Create .ssh directory for {{ user }}"
  become: true
  ansible.builtin.file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Generate SSH key
  become: true
  ansible.builtin.openssh_keypair:
    path: "/home/{{ user }}/.ssh/id_{{ user }}_{{ ansible_hostname }}"
    type: ed25519
    mode: "0400"
    owner: "{{ user }}"
    group: "{{ user }}"
