---
- name: Configure git
  become: true
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: git.j2
    dest: "/home/{{ user }}/.gitconfig"
    mode: "0600"
  tags: config

- name: Configure dotfiles in home
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - .zshrc
    - .zshenv
    - .editorconfig
    - .tmux.conf

- name: Add root editorconfig
  become: true
  ansible.builtin.copy:
    src: .editorconfig
    dest: /
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure installed apps
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - alacritty
    - i3
    - monitors.xml
    - picom
    - nvim
    - starship.toml
    - sway

- name: Configure greetd
  become: true
  ansible.builtin.copy:
    src: "greetd"
    dest: "/etc/"
    owner: "root"
    group: "root"
    mode: "0644"
  tags: config

- name: Configure i3status
  become: true
  ansible.builtin.template:
    src: "i3status.j2"
    dest: "/home/{{ user }}/.config/i3status/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure Zellij
  become: true
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "/home/{{ user }}/.config/zellij/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  tags: config
  loop:
    - { name: 'zellij/config.kdl', mode: '0644' }
    - { name: 'zellij/layouts', mode: '0644' }
    - { name: 'zellij/plugins', mode: '0750' }

- name: Configure Mate settings
  ansible.builtin.include_tasks: mate.yml
  tags: config
  when: ansible_facts['os_family'] == "Debian"

- name: Checkout Alacritty Themes
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty-theme
    dest: "/home/{{ user }}/.config/alacritty/themes"
    version: master
  tags: config

- name: Copy user specific scripts
  become: true
  ansible.builtin.copy:
    src: "bin"
    dest: "/home/{{ user }}/.local"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0750"
  tags: config

- name: Create xboxdrv config folder
  become: true
  ansible.builtin.file:
    path: "/etc/xboxdrv"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  tags: config

- name: Configure xboxdrv and add service
  become: true
  ansible.builtin.copy:
    src: "xboxdrv/{{ item.file }}"
    dest: "{{ item.folder }}/{{ item.file }}"
    owner: "root"
    group: "root"
    mode: "0644"
  tags: config
  loop:
    - { file: 'wiiu.xboxdrv', folder: '/etc/xboxdrv/' }
    - { file: 'xboxdrv.service', folder: '/etc/systemd/system/' }

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  tags: config

- name: Configure Wireguard tunnels (home and secondary site)
  become: true
  ansible.builtin.copy:
    src: "wireguard/{{ item }}"
    dest: "/etc/wireguard"
    owner: "root"
    group: "root"
    mode: "0644"
  tags: config
  loop:
    - wg0.conf
    - wg1.conf

- name: Enable services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  tags: config
  loop:
    - bluetooth
    - displaylink
