---
- name: Configure git
  become: true
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: git.j2
    dest: "/home/{{ user }}/.gitconfig"
    mode: "0600"
  tags: config

- name: Configure dotfiles in home
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - .zshrc
    - .zshenv
    - .editorconfig
    - .tmux.conf

- name: Add root editorconfig
  become: true
  ansible.builtin.copy:
    src: .editorconfig
    dest: /
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure installed apps
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - alacritty
    - i3
    - i3status
    - monitors.xml
    - picom
    - nvim
    - starship.toml

- name: Configure Zellij
  become: true
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "/home/{{ user }}/.config/zellij/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  tags: config
  loop:
    - { name: 'zellij/config.kdl', mode: '0644' }
    - { name: 'zellij/layouts', mode: '0644' }
    - { name: 'zellij/plugins', mode: '0750' }

- name: Configure Mate settings
  ansible.builtin.include_tasks: mate.yml
  tags: config

- name: Checkout Alacritty Themes
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty-theme
    dest: "/home/{{ user }}/.config/alacritty/themes"
    version: master
  tags: config

- name: Copy user specific scripts
  become: true
  ansible.builtin.copy:
    src: "bin"
    dest: "/home/{{ user }}/.local"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0750"
  tags: config
