---
- name: Configure git
  become: true
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: git.j2
    dest: "/home/{{ user }}/.gitconfig"
    mode: "0600"
  tags: config

- name: Configure zsh
  become: true
  ansible.builtin.copy:
    src: .zshrc
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure Neovim
  become: true
  ansible.builtin.copy:
    src: nvim
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Add root editorconfig
  become: true
  ansible.builtin.copy:
    src: .editorconfig
    dest: /
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure Starship
  become: true
  ansible.builtin.copy:
    src: starship.toml
    dest: "/home/{{ user }}/.config/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure Zellij
  become: true
  ansible.builtin.copy:
    src: zellij/config.kdl
    dest: "/home/{{ user }}/.config/zellij/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Copy statusbar to Zellij plugins folder
  become: true
  ansible.builtin.copy:
    src: zellij/plugins/statusbar.wasm
    dest: "/home/{{ user }}/.config/zellij/plugins/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0750"
  tags: config

- name: Create Zellij layouts directory
  become: true
  ansible.builtin.file:
    path: "/home/{{ user }}/.config/zellij/layouts"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: config

- name: Add Zellij layouts
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ user }}/.config/zellij/layouts/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - editor.kdl
    - terminal.kdl
