---
- name: Configure git
  become: true
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: git.j2
    dest: "/home/{{ user }}/.gitconfig"
    mode: "0600"
  tags: config

- name: Configure dotfiles in home
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - .zshrc
    - .zshenv
    - .editorconfig

- name: Add root editorconfig
  become: true
  ansible.builtin.copy:
    src: .editorconfig
    dest: /
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure installed apps
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - nvim
    - starship.toml
    - zellij
    - i3
    - i3status
    - alacritty

- name: Make Zellij statusbar executable
  become: true
  ansible.builtin.file:
    state: file
    path: "/home/{{ user }}/.config/zellij/plugins/statusbar.wasm"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0750"
  tags: config

- name: Add Zellij layouts
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ user }}/.config/zellij/layouts/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
  loop:
    - editor.kdl
    - terminal.kdl

- name: Configure Mate settings
  ansible.builtin.include_tasks: mate.yml
  tags: config

- name: Checkout Alacritty Themes
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty-theme
    dest: "/home/{{ user }}/.config/alacritty/themes"
    version: master
  tags: config
