---
- name: "Configure git"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: git.j2
    dest: "/home/{{ user }}/.gitconfig"
  tags: config

- name: "Configure zsh"
  become: true
  ansible.builtin.copy:
    src: .zshrc
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: config
