---
- name: Configure git
  become: true
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: git.j2
    dest: "/home/{{ user }}/.gitconfig"
    mode: "0600"
  tags: config

- name: Configure zsh
  become: true
  ansible.builtin.copy:
    src: .zshrc
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config

- name: Configure Neovim
  become: true
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "/home/{{ user }}/.config/{{ item.dest_dir }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  loop:
    - { name: 'init.lua', dest_dir: 'nvim' }
    - { name: 'set.lua', dest_dir: 'nvim/lua/config' }
  tags: config

- name: Configure Starship
  become: true
  ansible.builtin.copy:
    src: starship.toml
    dest: "/home/{{ user }}/.config/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  tags: config
