---
- name: Remove uneeded mate panel items
  become: true
  become_user: "{{ user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    state: absent
  loop:
    - key: '/org/mate/panel/toplevels/top'
    - key: '/org/mate/panel/toplevels/bottom'
    - key: '/org/mate/panel/objects/main-menu'
    - key: '/org/mate/panel/objects/window-list'
    - key: '/org/mate/panel/objects/clock-applet'
    - key: '/org/mate/panel/objects/main-menu'
  tags: config

- name: Set dconf settings
  become: true
  become_user: "{{ user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - key: '/org/mate/terminal/keybindings/zoom-normal'
      value: "'<Primary>0'"
    - key: '/org/mate/terminal/keybindings/copy'
      value: "'<Primary><Shift>c'"
    - key: '/org/mate/terminal/keybindings/paste'
      value: "'<Primary><Shift>v'"
    - key: '/org/mate/desktop/peripherals/keyboard/kbd/options'
      value: '["caps\\tcaps:escape"]'
    - key: '/org/mate/desktop/peripherals/keyboard/kbd/layouts'
      value: '["us\\talt-intl", "us"]'
    - key: '/org/mate/desktop/session/required-components/windowmanager'
      value: "'i3'"
    - key: '/org/mate/desktop/session/required-components-list'
      value: "['windowmanager', 'panel']"
    - key: '/org/mate/panel/general/object-id-list'
      value: "['object-1', 'object-9']"
    - key: '/org/mate/panel/general/toplevel-id-list'
      value: "['top']"
    - key: '/org/mate/desktop/session/required-components/panel'
      value: "'mate-panel'"
    - key: '/org/mate/panel/toplevels/top/auto-hide'
      value: "true"
    - key: '/org/mate/panel/toplevels/top/enable-buttons'
      value: "false"
    - key: '/org/mate/panel/toplevels/top/auto-hide'
      value: "true"
    - key: '/org/mate/panel/toplevels/top/expand'
      value: "true"
    - key: '/org/mate/panel/toplevels/top/orientation'
      value: "'top'"
    - key: '/org/mate/panel/toplevels/top/screen'
      value: "0"
    - key: '/org/mate/panel/toplevels/top/size'
      value: "19"
    - key: '/org/mate/panel/toplevels/top/x-centered'
      value: "true"
    - key: '/org/mate/desktop/background/color-shading-type'
      value: "'vertical-gradient'"
    - key: '/org/mate/desktop/background/picture-filename'
      value: "'/usr/share/backgrounds/mate/desktop/Ubuntu-Mate-Warm-no-logo.png'"
    - key: '/org/mate/desktop/background/picture-options'
      value: "'zoom'"
    - key: '/org/mate/desktop/interface/gtk-theme'
      value: "'BlackMATE'"
    - key: '/org/mate/desktop/interface/icon-theme'
      value: "'mate'"
  tags: config
